# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v2
kind: SiteConfig
metadata:
  name: "ljlabocp3"
  namespace: "ljlabocp3"
spec:
  baseDomain: "benoibm.com"
  pullSecretRef:
    name: "ljlabocp3-ztp-pull-secret"
  clusterImageSetNameRef: "img4.15.13-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINUOIHxvSqh3aJDQw9JbHHoEW09CRJDOG0cwliY8mRSH borazem@al-borazem.ssclab.ibm.si"
  clusters:
  - clusterName: "ljlabocp3"
    networkType: "OVNKubernetes"
    # installConfigOverrides is a generic way of passing install-config
    # parameters through the siteConfig.  The 'capabilities' field configures
    # the composable openshift feature.  In this 'capabilities' setting, we
    # remove all but the marketplace component from the optional set of
    # components.
    # Notes:
    # - OperatorLifecycleManager is needed for 4.15 and later
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    # installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"OperatorLifecycleManager\", \"NodeTuning\" ] }}"
    installConfigOverrides: | 
      {
        "capabilities": {
          "baselineCapabilitySet": "None",
          "additionalEnabledCapabilities": [
            "NodeTuning",
            "OperatorLifecycleManager",
            "Console"
          ]
        }
      }
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      # du-profile: "latest"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      # group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "ljlabocp3"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.200.0.0/16
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 10.0.10.100
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    cpuPartitioningMode: AllNodes
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "master2.ljlabocpsn2.benoibm.com"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia://10.200.97.143/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "ljlabocp3-bmh-secret"
        bootMACAddress: "7C:D3:0A:6A:6B:D0"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
        #  wwn: "0x11111000000asd123"
        # example of diskPartition below is used for image registry (check ImageRegistry.md for more details), but it's not limited to this use case
#        diskPartition:
#          - device: /dev/disk/by-id/wwn-0x11111000000asd123 # match rootDeviceHints
#            partitions:
#              - mount_point: /var/imageregistry
#                size: 102500
#                start: 344844
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "7C:D3:0A:6A:6B:D0"
            - name: eno2
              macAddress: "7C:D3:0A:6A:6B:D1"
          config:
            interfaces:
              - name: bond0.200 
                type: vlan 
                state: up
                vlan:
                  base-iface: bond0
                  id: 200
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.200.170.25
                      prefix-length: 16
                  dhcp: false
              - name: bond0 
                type: bond 
                state: up
                mac-address: 7C:D3:0A:6A:6B:D0
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad 
                  options:
                    miimon: "150" 
                  port:
                   - eno1
                   - eno2
            dns-resolver: 
              config:
                search:
                  - ljlabocp3.benoibm.com
                server:
                  - 10.0.10.100
                  - 10.0.10.101
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: 10.200.0.1 
                  next-hop-interface: bond0.200 
                  table-id: 254